name: CI
on:
    push:
        branches:
            - main

jobs:
    contrib-readme-job:
        runs-on: ubuntu-latest
        name: A job to automate contribute list in contributors.md
        steps:
            - name: Contribute List
              uses: akhilmhdh/contributors-readme-action@master
              with:
                  readme_path: "CONTRIBUTORS.md"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}